In [1]:
import tensorflow as tf

In [2]:
tensor_1 = tf.constant(1)
print(tensor_1)
tensor_2 = tf.constant([1.0, 2.0])
print(tensor_2)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [3]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[5, 6],
                 [7, 8]])

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 



In [4]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
b = tf.constant([[10, 20],
                 [30, 40],
                 [50, 60]])

print(a @ b, "\n") # matrix multiplication


b,a = a,b
print(a @ b, "\n") 

tf.Tensor(
[[220 280]
 [490 640]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 90 120 150]
 [190 260 330]
 [290 400 510]], shape=(3, 3), dtype=int32) 



In [5]:
e = tf.einsum('ij,jk->ik', a, b) # matrix multiplication
print(e.shape)
print(e)

(3, 3)
tf.Tensor(
[[ 90 120 150]
 [190 260 330]
 [290 400 510]], shape=(3, 3), dtype=int32)


In [6]:
c = tf.constant([[1, 2],
                 [3, 4]])
d = tf.constant([[5, 6],
                 [7, 8]])

e = tf.einsum('ij->ji', e) # transpose
print(e)

tf.Tensor(
[[ 90 190 290]
 [120 260 400]
 [150 330 510]], shape=(3, 3), dtype=int32)


In [7]:
f = tf.einsum('ii->i', e) # diagonal
print(f)

tf.Tensor([ 90 260 510], shape=(3,), dtype=int32)


In [10]:
trace = tf.einsum('ii', e)  # output[j,i] = trace(m) = sum_i m[i, i]
assert trace == sum(f)
print(trace.shape)
print(trace)
print(sum(f))


()
tf.Tensor(860, shape=(), dtype=int32)
tf.Tensor(860, shape=(), dtype=int32)
