In [1]:
import torch

In [2]:
tensor1D = torch.tensor([1,2,3,4])
tensor1D

tensor([1, 2, 3, 4])

In [3]:
float(tensor1D[0]), float(tensor1D[1])

(1.0, 2.0)

In [4]:
tensor2D = torch.tensor([[1,2],[3,4]])
tensor2D
tensor2D.storage()

 1
 2
 3
 4
[torch.LongStorage of size 4]

In [5]:
tensor2D.storage()[3]

4

In [6]:
tensor2D.storage()[3] = 5
tensor2D.storage()[3]

5

In [11]:
tensor2D = torch.tensor([[1,2],[3,4],[5,6]])
tensor2D

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
tensor2D.t()

tensor([[1, 3, 5],
        [2, 4, 6]])

In [15]:
tensor2D.stride()

(2, 1)

In [16]:
tensor2D.t().stride()

(1, 2)

In [19]:
tensor2D.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [20]:
tensor2D.zero_()

tensor([[0, 0],
        [0, 0],
        [0, 0]])